# Generated by Django 3.1.3 on 2020-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20201202_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_code',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
