# Generated by Django 3.1.3 on 2020-12-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='departments.job'),
        ),
    ]
