# Generated by Django 3.1.3 on 2020-12-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_auto_20201203_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='departments.job'),
        ),
    ]
