# Generated by Django 3.1.3 on 2020-12-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_auto_20201203_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(to='departments.Job'),
        ),
    ]
