# Generated by Django 3.1.3 on 2020-12-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_employee_job_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='departments.job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_starting_date',
            field=models.DateTimeField(null=True),
        ),
    ]
