# Generated by Django 3.1.3 on 2020-12-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0011_auto_20201204_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='days_on_vacation',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='departments.employee')),
            ],
        ),
    ]
